export const tripData = {
  welcome: {
    quote: "Thousands of tired, nerve-shaken, over-civilized people are beginning to find out that going to the mountains is going home; that wildness is a necessity.",
    author: "John Muir",
    subtitle: "The mountains are calling — let's answer together.",
  },
  overview: {
    dates: "January 16-18, 2026",
    travelers: ["Suraj", "Ridhima", "Roshni", "Manoj"],
    startPoint: "San Jose, CA",
    parkEntry: "$35 per vehicle (7-day pass)",
    tripSpirit: "This weekend is about fun, exploration, adventure, and connecting with nature. Take your time. Breathe deep. Let the granite walls and ancient trees remind you how magnificent our world is. As John Muir wrote: 'In every walk with nature one receives far more than he seeks.'",
    emergencyNumbers: [
      { name: "Yosemite Emergency", phone: "911" },
      { name: "Park Information", phone: "(209) 372-0200" },
      { name: "Road Conditions", phone: "(209) 372-0200 (press 1, then 1)" },
      { name: "Caltrans Road Info", phone: "1-800-427-7623" },
      { name: "Yosemite Medical Clinic", phone: "(209) 372-4637" },
    ],
    winterTips: [
      "Carry tire chains - REQUIRED by law even with 4WD/AWD",
      "Check road conditions before departing each day",
      "Bring microspikes/traction devices for icy trails",
      "Layer clothing - temps range 25-50°F",
      "Sunrise ~7:14 AM, Sunset ~5:15 PM in mid-January",
      "Some trails may be icy - bring trekking poles",
      "Water fountains at trailheads may be closed - bring your own",
      "Shorter daylight hours - plan activities accordingly",
    ],
  },
  days: [
    {
      day: 1,
      date: "Friday, January 16",
      title: "Evening Departure & Scenic Drive",
      theme: "Night Journey to Yosemite",
      activities: [
        {
          time: "6:00 PM",
          title: "Depart San Jose",
          type: "drive",
          description: "Leave after work. Drive via CA-152 E to I-5 S to CA-140 E (Mariposa route - most scenic and safest winter route).",
          duration: "3.5-4 hours",
          mapUrl: "https://www.google.com/maps/dir/San+Jose,+CA/El+Portal,+CA",
          tips: ["Fill up gas in San Jose", "Pack snacks for the drive", "Download offline maps"],
        },
        {
          time: "7:30 PM",
          title: "Dinner Stop - Los Banos or Merced",
          type: "food",
          description: "Quick dinner break along the route.",
          options: [
            { name: "In-N-Out Burger (Los Banos)", address: "1320 Pacheco Blvd, Los Banos, CA", phone: "(800) 786-1000", hours: "10:30 AM - 1:00 AM", mapUrl: "https://www.google.com/maps/place/In-N-Out+Burger/@37.0544,-120.8498", note: "Veggie burger and grilled cheese available" },
            { name: "Chipotle (Merced)", address: "645 W Olive Ave, Merced, CA", phone: "(209) 388-9449", hours: "10:45 AM - 10:00 PM", mapUrl: "https://www.google.com/maps/place/Chipotle+Mexican+Grill/@37.3022,-120.4829", note: "Great vegetarian/sofritas options" },
          ],
        },
        {
          time: "10:00 PM",
          title: "Arrive at Lodging",
          type: "lodging",
          description: "Check into your accommodation near Yosemite. Rest up for a late start tomorrow!",
          tips: ["Confirm check-in procedures", "Sleep in - no early alarm needed", "Prep camera gear for afternoon"],
        },
      ],
    },
    {
      day: 2,
      date: "Saturday, January 17",
      title: "Valley Sampler: Waterfalls, Meadows & Views",
      theme: "Scenic Variety with Built-in Breaks",
      activities: [
        {
          time: "10:00 AM",
          title: "Depart Lodging",
          type: "drive",
          description: "Relaxed late start after last night's drive. Breakfast at home with your supplies. Head into Yosemite Valley.",
          duration: "Entry + drive to valley",
          tips: ["Have a good breakfast at home", "Pack lunch and snacks for the day", "Fill water bottles before leaving"],
        },
        {
          time: "11:00 AM",
          title: "El Capitan Meadow",
          type: "photo",
          description: "First stop: El Capitan Meadow for close-up views of the famous granite monolith. Look for climbers on the wall with binoculars!",
          duration: "30 minutes",
          address: "El Capitan Meadow, Northside Dr, Yosemite Valley",
          mapUrl: "https://www.google.com/maps/place/El+Capitan+Meadow/@37.7244,-119.6377",
          trivia: "The Ahwahneechee people called El Capitan 'Tutokanula' meaning 'Rock Chief.' At 3,000 feet, it's the largest granite monolith in the world. The first successful climb took 47 days in 1958! Today, elite climbers can summit in under 2 hours.",
          photoTips: ["Late morning light works well", "Bring binoculars to spot climbers", "Reflection shots possible if meadow has standing water"],
        },
        {
          time: "11:45 AM",
          title: "🥾 Bridalveil Fall Trail",
          type: "hike",
          description: "Short walk to the base of this iconic 620-foot waterfall. You'll feel the mist! The falls may have icicles in winter - beautiful for photos.",
          duration: "20-30 minutes",
          distance: "0.5 miles round trip",
          elevation: "80 ft gain",
          difficulty: "Easy",
          mapUrl: "https://www.google.com/maps/place/Bridalveil+Fall+Trailhead/@37.7166,-119.6516",
          alltrailsUrl: "https://www.alltrails.com/trail/us/california/bridalveil-fall-trail",
          trivia: "The Ahwahneechee called this 'Pohono' - Spirit of the Puffing Wind. Legend says the mist contains spirits that blessed visitors. The swirling winds really do make the water dance like a bride's veil! It's one of the few Yosemite waterfalls that flows year-round.",
          tips: ["Trail can be icy - watch your step", "Bring waterproof layer - you'll get misty!", "Great morning light for photos"],
        },
        {
          time: "12:30 PM",
          title: "🥾 Cook's Meadow Loop",
          type: "hike",
          description: "Flat, easy loop through the heart of Yosemite Valley with 360° views of Half Dome, Yosemite Falls, Sentinel Rock, and Glacier Point. Boardwalk trail perfect for photos!",
          duration: "30-45 minutes",
          distance: "1.1 miles loop",
          elevation: "Flat (29 ft)",
          difficulty: "Easy",
          trailhead: "Sentinel Bridge (Shuttle Stop #11) or Visitor Center",
          mapUrl: "https://www.google.com/maps/place/Cook's+Meadow+Loop/@37.7453,-119.5893",
          alltrailsUrl: "https://www.alltrails.com/trail/us/california/cook-s-meadow-trail",
          trivia: "The Ahwahneechee lived in this valley for over 3,000 years before European contact. 'Yosemite' comes from the Miwok word 'uzumati' meaning grizzly bear - other tribes called the valley's inhabitants 'Yosemites' because they were skilled bear hunters!",
          highlights: ["Sentinel Bridge - classic Half Dome reflection shot", "Yosemite Chapel - charming 1879 chapel with falls backdrop", "Swinging Bridge - views upstream to Yosemite Falls"],
        },
        {
          time: "1:30 PM",
          title: "Lunch at Curry Village",
          type: "food",
          description: "Refuel with pizza at the Pizza Deck! Great vegetarian and chicken options.",
          options: [{ name: "Curry Village Pizza Deck", address: "9010 Curry Village Dr, Yosemite Valley", phone: "(209) 372-8333", hours: "Sat 12:00 PM - 9:00 PM", price: "$$", priceNote: "$20-35 for a pizza", mapUrl: "https://www.google.com/maps/place/Curry+Village+Pizza+Deck", note: "Order at window. Veggie & chicken pizza available!", mustTry: ["Vegetarian Pizza", "Chicken Pizza", "Cheesy Garlic Bread"] }],
        },
        {
          time: "2:30 PM",
          title: "🥾 Vernal Fall Footbridge",
          type: "hike",
          description: "Moderate hike along the Merced River to the footbridge with stunning views of Vernal Falls. This is the perfect turnaround point in winter - you get the views without the strenuous climb!",
          duration: "1-1.5 hours",
          distance: "1.8 miles round trip",
          elevation: "400 ft gain",
          difficulty: "Moderate",
          trailhead: "Happy Isles Trailhead (Shuttle Stop #16)",
          mapUrl: "https://www.google.com/maps/place/Happy+Isles+Trailhead/@37.7319,-119.5580",
          alltrailsUrl: "https://www.alltrails.com/trail/us/california/vernal-fall-foot-bridge-via-john-muir-trail",
          trivia: "Vernal Fall drops 317 feet and was named by Lafayette Bunnell in 1851 who said it reminded him of springtime - 'an eternal April.' The Ahwahneechee called it 'Yan-o-pah' meaning Little Cloud. In peak spring flow, 1,200 cubic feet of water cascade over every second!",
          winterConditions: ["Paved trail to footbridge - can be icy in spots", "Restrooms and water at the footbridge", "Turn around here - Mist Trail beyond is closed in winter", "Bring microspikes just in case"],
          note: "This is the sweet spot! Great Vernal Falls views without the 5-hour commitment.",
        },
        {
          time: "4:00 PM",
          title: "🥾 Mirror Lake",
          type: "hike",
          description: "In winter, Mirror Lake actually has water (unlike summer when it's a meadow!). The calm water creates stunning reflections of Half Dome. Best photos in late afternoon light.",
          duration: "45 minutes - 1 hour",
          distance: "2 miles round trip",
          elevation: "Flat",
          difficulty: "Easy",
          trailhead: "Mirror Lake Trailhead (Shuttle Stop #17)",
          mapUrl: "https://www.google.com/maps/place/Mirror+Lake/@37.7445,-119.5556",
          alltrailsUrl: "https://www.alltrails.com/trail/us/california/mirror-lake-via-valley-loop-trail",
          trivia: "Mirror Lake is slowly filling with sediment - it's a temporary geological feature! In summer it's often just a meadow, but winter snowmelt fills it with reflective water. The Ahwahneechee called Half Dome 'Tis-sa-ack' after a woman in their creation story whose tears formed the rock's dark streaks.",
          photoTips: ["Arrive when it's calm for best reflections", "Half Dome reflection is the money shot", "May be partially frozen - even more beautiful!"],
        },
        {
          time: "5:15 PM",
          title: "🌅 Tunnel View Sunset",
          type: "photo",
          description: "Head to Tunnel View for sunset. The setting sun lights up El Capitan in golden hues. Stay for the alpenglow on Half Dome!",
          duration: "45 minutes",
          mapUrl: "https://www.google.com/maps/place/Tunnel+View/@37.7156,-119.6778",
          trivia: "This viewpoint was created when the Wawona Tunnel was built in 1933. Ansel Adams captured his famous 'Clearing Winter Storm' photo near here. In 1903, John Muir and President Theodore Roosevelt camped in the park - that trip inspired Roosevelt to protect Yosemite!",
          photoTips: ["Sunset around 5:15 PM in January", "Stay 20 mins after for alpenglow on Half Dome", "Purple/pink skies often appear after sunset", "Tripod recommended for low light"],
        },
        {
          time: "6:30 PM",
          title: "Dinner at Home",
          type: "food",
          description: "Head back to lodging for a cozy dinner with your supplies. You've earned a relaxing evening after all that hiking!",
          tips: ["Use your groceries from home", "Hot soup or pasta hits the spot after a day of hiking", "Recharge for tomorrow's early sunrise"],
        },
        {
          time: "8:30 PM",
          title: "⭐ Optional: Stargazing at Cook's Meadow",
          type: "stargazing",
          optional: true,
          description: "If you're not too tired, bundle up and head back to Cook's Meadow for stargazing! Winter offers the darkest, clearest skies. The boardwalk keeps you away from artificial lights, and the open meadow gives you 360° views of the stars above the granite walls.",
          duration: "30 min - 1 hour",
          mapUrl: "https://www.google.com/maps/place/Cook's+Meadow/@37.7453,-119.5893",
          tips: ["Dress VERY warm - temps drop to 20s°F", "Bring headlamp with red light mode to preserve night vision", "Download a star chart app (Sky Guide, Star Walk)", "Give your eyes 20 mins to adjust to darkness", "Look for Orion, the Big Dipper, and the Milky Way", "El Capitan Meadow is another great option - you might see climbers' headlamps on the wall!"],
          trivia: "Yosemite has virtually no light pollution - on clear nights you can see 2,000+ stars and even the Andromeda Galaxy (2.5 million light years away!) with the naked eye. Winter constellations like Orion are especially prominent in January.",
        },
        {
          time: "9:30 PM",
          title: "Return to Lodging",
          type: "drive",
          description: "Rest up for early sunrise tomorrow!",
          tips: ["Set alarm for 6:00 AM for sunrise", "Prep camera gear tonight", "Charge all batteries"],
        },
      ],
    },
    {
      day: 3,
      date: "Sunday, January 18",
      title: "Sunrise, Sledding & Giant Sequoias",
      theme: "Sunrise, Snow Play & Ancient Trees",
      activities: [
        {
          time: "6:00 AM",
          title: "Early Wake-Up & Breakfast at Home",
          type: "food",
          description: "Quick breakfast with your supplies before heading to catch sunrise at Tunnel View.",
          tips: ["Have breakfast ready to go", "Bring thermos with hot coffee/tea for the road", "Dress in warm layers - temps in 20s°F at dawn"],
        },
        {
          time: "6:45 AM",
          title: "🌄 Tunnel View Sunrise",
          type: "photo",
          description: "The iconic Yosemite viewpoint. Arrive before sunrise (7:14 AM) to catch first light on El Capitan and Half Dome. In winter, morning fog often fills the valley creating magical scenes.",
          duration: "1 hour",
          address: "Tunnel View, Wawona Rd, Yosemite Valley, CA",
          mapUrl: "https://www.google.com/maps/place/Tunnel+View/@37.7156,-119.6778",
          trivia: "The valley fog you might see is actually 'temperature inversion' - cold air trapped below warmer air. John Muir called Yosemite 'by far the grandest of all the special temples of Nature I was ever permitted to enter.'",
          photoTips: ["Use tripod for long exposures", "Fog creates amazing depth - embrace it", "Stay 20-30 mins after sunrise for best colors", "Wide angle lens recommended (17-35mm)"],
        },
        {
          time: "8:00 AM",
          title: "🥾 Lower Yosemite Falls",
          type: "hike",
          description: "Easy morning loop with views of North America's tallest waterfall. January flow may be reduced but the ice formations can be spectacular!",
          duration: "30-45 minutes",
          distance: "1 mile loop",
          elevation: "50 ft gain",
          difficulty: "Easy",
          trailhead: "Lower Yosemite Fall Trailhead (Shuttle Stop #6)",
          mapUrl: "https://www.google.com/maps/place/Lower+Yosemite+Fall/@37.7453,-119.5962",
          alltrailsUrl: "https://www.alltrails.com/trail/us/california/lower-yosemite-falls-trail",
          trivia: "Yosemite Falls is the tallest waterfall in North America at 2,425 feet - nearly half a mile! It's actually three falls in one: Upper (1,430 ft), Middle Cascades (675 ft), and Lower (320 ft). In winter, an ice cone forms at the base from frozen spray - it can reach 200+ feet tall!",
          tips: ["Look for ice cone at base of Upper Fall", "Paved trail - accessible year-round", "Great spot for photos looking up at both falls"],
        },
        {
          time: "9:00 AM",
          title: "Drive to Crane Flat",
          type: "drive",
          description: "Head north on Big Oak Flat Road to Crane Flat snow play area - the only designated sledding area inside Yosemite National Park!",
          duration: "30 minutes from valley",
          mapUrl: "https://www.google.com/maps/dir/Yosemite+Valley/Crane+Flat,+Yosemite+National+Park",
        },
        {
          time: "9:30 AM",
          title: "🛷 Crane Flat Snow Play - Sledding!",
          type: "sledding",
          description: "Time for winter fun! Crane Flat (elevation 6,200 ft) is the only designated snow play area inside Yosemite. Located near the Crane Flat Campground, with sledding hills among the trees and open meadows for snowball fights!",
          duration: "1.5-2 hours",
          address: "Crane Flat Campground turnoff, Highway 120, Yosemite",
          mapUrl: "https://www.google.com/maps/place/Crane+Flat/@37.7547,-119.8203",
          trivia: "Crane Flat got its name from the sandhill cranes that once gathered here during migration. At 6,200 feet, it gets significantly more snow than the valley floor (4,000 ft). The Tuolumne Grove of giant sequoias is just a 1-mile hike from here!",
          tips: ["Bring your own sleds - no rentals available", "Portable restrooms on access road", "Gas station nearby at Tioga Road junction", "Higher elevation = better snow than valley", "Parking can be limited - arrive early"],
          note: "⚠️ Check NPS conditions page or call (209) 372-0200 to confirm snow levels before going",
        },
        {
          time: "11:30 AM",
          title: "Drive to Mariposa Grove",
          type: "drive",
          description: "Head south through the park via Big Oak Flat Road → Wawona Road (CA-41) to Mariposa Grove Welcome Plaza.",
          duration: "1.5 hours",
          mapUrl: "https://www.google.com/maps/dir/Crane+Flat/Mariposa+Grove+Welcome+Plaza",
        },
        {
          time: "1:00 PM",
          title: "🌲 Mariposa Grove - Grizzly Giant Loop Trail",
          type: "hike",
          description: "WINTER ACCESS: The shuttle doesn't run in winter, so you'll hike the Washburn Trail from the Welcome Plaza to reach the grove. Once there, take the easy Grizzly Giant Loop to see the most famous trees. You'll likely have the grove nearly to yourself!",
          duration: "3-3.5 hours total",
          hikeDetails: [
            { segment: "Washburn Trail (to grove)", distance: "2 miles one-way", elevation: "500 ft gain", difficulty: "Moderate" },
            { segment: "Grizzly Giant Loop", distance: "2 miles loop", elevation: "300 ft gain", difficulty: "Easy" },
            { segment: "Total round trip", distance: "6 miles", elevation: "800 ft total gain", difficulty: "Moderate" },
          ],
          trailhead: "Mariposa Grove Welcome Plaza",
          mapUrl: "https://www.google.com/maps/place/Mariposa+Grove+Welcome+Plaza/@37.5025,-119.6109",
          alltrailsUrl: "https://www.alltrails.com/trail/us/california/grizzly-giant-loop-trail",
          trivia: "'Wawona' comes from the Miwok imitation of an owl's hoot - owls were believed to be guardian spirits of the sequoias. The Grizzly Giant is ~2,700 years old - it was already 700 years old when the Roman Empire fell! Giant sequoias can only grow naturally in a 60-mile stretch of the Sierra Nevada.",
          mustSee: ["Grizzly Giant - ~2,700 years old, largest tree in grove", "California Tunnel Tree - walk through a living giant", "Bachelor and Three Graces - beautiful cluster of 4 trees", "Fallen Monarch - famous hollow fallen tree near start"],
          winterConditions: ["No shuttle in winter - 2 mi hike to grove on Washburn Trail", "Trail may be snowy/icy - microspikes recommended", "Bring trekking poles for stability", "Pack snacks and 2L water - no services in grove", "Start by 1 PM to finish before dark (~5:15 PM sunset)"],
        },
        {
          time: "4:30 PM",
          title: "Depart for San Jose",
          type: "drive",
          description: "Head home via CA-41 S through Fish Camp and Oakhurst, then CA-99 or CA-41 to CA-152 W to San Jose.",
          duration: "3.5-4 hours",
          mapUrl: "https://www.google.com/maps/dir/Mariposa+Grove+Welcome+Plaza/San+Jose,+CA",
          note: "Goat Meadow Snowplay Area is on the way out (near Fish Camp) if Crane Flat didn't have snow",
        },
        {
          time: "5:30 PM",
          title: "Dinner on the Road",
          type: "food",
          description: "Quick dinner stop - McDonald's, In-N-Out, or whatever looks good along the way!",
          options: [
            { name: "McDonald's (Oakhurst)", address: "40044 CA-41, Oakhurst, CA", hours: "Open late", mapUrl: "https://www.google.com/maps/search/McDonalds+Oakhurst+CA" },
            { name: "In-N-Out (Fresno)", address: "Multiple locations on CA-99", note: "Veggie burger available" },
          ],
        },
        { time: "9:00 PM", title: "Arrive San Jose", type: "arrival", description: "Home after an amazing winter Yosemite adventure! 🏔️" },
      ],
    },
  ],
  packingList: {
    clothing: ["Warm base layers (merino wool recommended)", "Insulated mid-layer (fleece or down jacket)", "Waterproof outer shell jacket", "Waterproof pants or snow pants (for sledding!)", "Warm beanie and gloves (bring extras)", "Wool hiking socks (3+ pairs)", "Waterproof hiking boots", "Sunglasses"],
    gear: ["Sleds/saucers/tubes (bring your own!)", "Microspikes/traction cleats (ESSENTIAL)", "Trekking poles", "Headlamp with extra batteries", "Backpack (20-30L)", "Water bottles (2L per person)", "Snacks and trail food", "Hand/toe warmers", "Sunscreen (snow reflects UV)", "Thermos for hot drinks"],
    carEssentials: ["Tire chains (REQUIRED by law)", "Ice scraper/snow brush", "Blankets", "Flashlight", "First aid kit", "Phone chargers", "Offline maps downloaded", "Yosemite park pass"],
    photography: ["Camera + extra batteries (cold drains fast)", "Wide angle lens (16-35mm)", "Telephoto lens (70-200mm)", "Tripod", "Lens cloths", "Waterproof camera bag cover", "ND filters for waterfalls", "Remote shutter release"],
  },
  hikingSummary: {
    saturday: {
      title: "Valley Sampler - 4 Easy/Moderate Hikes",
      totalDistance: "5.4 miles",
      totalElevation: "~510 ft",
      hikes: [
        { name: "Bridalveil Fall", distance: "0.5 mi", elevation: "80 ft", difficulty: "Easy" },
        { name: "Cook's Meadow Loop", distance: "1.1 mi", elevation: "Flat", difficulty: "Easy" },
        { name: "Vernal Fall Footbridge", distance: "1.8 mi", elevation: "400 ft", difficulty: "Moderate" },
        { name: "Mirror Lake", distance: "2 mi", elevation: "Flat", difficulty: "Easy" },
      ],
    },
    sunday: {
      title: "Falls, Sledding & Sequoias",
      totalDistance: "7 miles",
      totalElevation: "~850 ft",
      hikes: [
        { name: "Lower Yosemite Falls", distance: "1 mi", elevation: "50 ft", difficulty: "Easy" },
        { name: "Mariposa Grove (total)", distance: "6 mi", elevation: "800 ft", difficulty: "Moderate" },
      ],
    },
  },
  stargazingInfo: {
    title: "Stargazing in Yosemite",
    bestSpots: ["Cook's Meadow - boardwalk keeps you away from lights, 360° views", "El Capitan Meadow - dramatic granite backdrop, might see climbers' headlamps"],
    tips: ["Winter has the darkest, clearest skies", "New moon = best visibility", "Give eyes 20 minutes to adjust", "Dress VERY warm - temps drop to 20s°F", "Bring red-light headlamp to preserve night vision"],
    whatToSee: ["Orion (the Hunter) - prominent in winter sky", "The Big Dipper / Ursa Major", "The Milky Way stretching overhead", "Andromeda Galaxy (on clear nights)", "Winter constellations: Taurus, Gemini, Canis Major"],
  },
  glacierPointNote: {
    title: "⚠️ Glacier Point Access in Winter",
    content: "Glacier Point Road is CLOSED to vehicles past Badger Pass Ski Area in winter. To reach Glacier Point, you would need to cross-country ski or snowshoe 10.5 miles ONE WAY (21 miles round trip). This is an expert-level full-day or overnight adventure, not feasible for a weekend trip. The views from Tunnel View, El Capitan Meadow, and the valley floor are excellent alternatives in winter.",
  },
  feasibilityNotes: [
    { activity: "Valley Sampler (4 hikes)", status: "Recommended!", details: "Bridalveil Fall, Cook's Meadow, Vernal Fall Footbridge, and Mirror Lake give you variety with built-in breaks. Total: 5.4 mi, ~510 ft gain." },
    { activity: "Mariposa Grove Giants", status: "Accessible with Extra Hiking", details: "Grove is open but shuttle doesn't run. Washburn Trail: 2 mi to grove (500 ft gain), then Grizzly Giant Loop: 2 mi (300 ft gain). Total: 6 mi RT, 800 ft gain." },
    { activity: "Crane Flat Sledding", status: "Check Snow Conditions", details: "Only designated snow play area INSIDE the park. At 6,200 ft elevation. Call (209) 372-0200 to confirm snow before going." },
    { activity: "Goat Meadow Sledding (backup)", status: "Check Snow Conditions", details: "Outside park near Fish Camp. At 5,200 ft - lower elevation may mean less snow. On your way out if Crane Flat doesn't have snow." },
    { activity: "El Capitan", status: "Fully Accessible", details: "View from valley floor at El Capitan Meadow. One of the best winter viewing experiences!" },
    { activity: "Glacier Point", status: "NOT Feasible", details: "Road closed. Would require 21-mile round trip ski/snowshoe. Not recommended for weekend trip." },
    { activity: "Tunnel View", status: "Fully Accessible", details: "Open year-round. Best at sunrise, sunset, and night. Perfect for this trip!" },
  ],
};
